### ISSUE TITLE
[Easy] Update project description in README

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/oreiller#4]
Tasks

- Delete line 5 of README
https://github.com/Abdur-rahmaanJ/oreiller/blob/05d320e626c9dc4cc1a731a38a538777d23d76ac/README.md?plain=1#L5

- Replace line 3 of the README by this line "The package for easy image manipulation backed by pillow power."

**Comment by Mohamed-AH** [comment]
I would like to do this task

**Comment by Abdur-rahmaanJ** [comment]
@Mohamed-AH Done!

**Comment by Abdur-rahmaanJ** [comment]
Solved using #7
